music_directory    "/home/teavostok1/Music"
playlist_directory "/home/teavostok1/.config/mpd/playlists"
db_file            "/home/teavostok1/.config/mpd/database"
log_file           "/home/teavostok1/.config/mpd/log"
pid_file           "/home/teavostok1/.config/mpd/pid"
state_file         "/home/teavostok1/.config/mpd/state"

user                "teavostok1"
bind_to_address     "/home/teavostok1/.config/mpd/socket"
port                "6600"
auto_update         "yes"
auto_update_depth   "3"
follow_outside_symlinks "yes"
follow_inside_symlinks  "yes"

audio_output {
  type  "pipewire"
  name  "PipeWire"
}

input {
  plugin "curl"
}
