music_directory    ~/Music
playlist_directory ~/.config/mpd/playlists
db_file            ~/.config/mpd/database
log_file           ~/.config/mpd/log
pid_file           ~/.config/mpd/pid
state_file         ~/.config/mpd/state
socket             ~/.config/mpd/socket

user                teavostok1
bind_to_address     ~/.config/mpd/socket
port                6600
auto_update         yes
auto_update_depth   3
follow_outside_symlinks yes
follow_inside_symlinks  yes

audio_output {
  type  "pipewire"
  name  "PipeWire"
}

input {
  plugin "curl"
}
